{
  lib,
  pkgs,
  config,
  ...
}:
let
  taskList = lib.ros.dag.topoSort config.taskOrder;
in
{
  options.ros.script = lib.mkOption {
    type = lib.types.package;
  };

  config = {
    assertions = [
      {
        assertion = taskList ? result;
        message = ''
          Topological sorting of tasks failed, likely due to an ordering cyclus.
          ${builtins.toJSON taskList}
        '';
      }
    ];

    ros.script =
      let
        # TODO; Combine with user scripts
        configPaths = map (pathEntries: pathEntries.data) taskList.result;
        conceptBlocks = map (path: lib.attrByPath path null config) configPaths;
        createRules = map (concept: concept._create) conceptBlocks;
      in
      pkgs.writeText "TODO" ''
        # Generated by NixOS-to-RouterOS Compiler
        # Warning: Do not edit manually!

        ${lib.concatStringsSep "\n" createRules}
      '';
  };
}
